# Generated by Django 5.2.6 on 2025-09-15 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('name_ar', models.CharField(max_length=100)),
                ('name_it', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Surah',
            },
        ),
        migrations.CreateModel(
            name='Ayah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.surah')),
            ],
            options={
                'verbose_name_plural': 'Ayah',
                'unique_together': {('surah', 'number')},
            },
        ),
        migrations.CreateModel(
            name='TafsirText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ar', models.TextField()),
                ('ayah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tafsir_texts', to='editor.ayah')),
            ],
            options={
                'verbose_name_plural': 'Tafsir Texts',
            },
        ),
        migrations.CreateModel(
            name='TafsirTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arabic_selection', models.TextField()),
                ('translation_it', models.TextField()),
                ('start_index', models.PositiveIntegerField()),
                ('end_index', models.PositiveIntegerField()),
                ('tafsir_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='editor.tafsirtext')),
            ],
            options={
                'unique_together': {('tafsir_text', 'start_index', 'end_index')},
            },
        ),
    ]
