# Generated by Django 5.2.6 on 2025-10-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tafsirtext',
            name='text_tashkeel',
            field=models.TextField(blank=True, null=True),
        ),
    ]
