# Generated by Django 5.2.6 on 2025-10-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_tafsirtext_text_tashkeel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tafsirtranslation',
            name='end_index_tashkeel',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tafsirtranslation',
            name='start_index_tashkeel',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
